### PR TITLE
Bumps xcode, python versions as MacOS marches on

### PR DESCRIPTION
**Pull request by rjrjr**
* Xcode_15.1.app
* Python 3.12.3

### CODE REVIEW

**Comment by rjrjr** [comment]
Testing: https://github.com/square/workflow/actions/runs/8885942437

**Comment by rjrjr** [comment]
Need to bump python as well:

```
The version '3.10.10' with architecture 'arm64' was not found for macOS 14.4.1. The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.jsonShow less
```

**Comment by rjrjr** [comment]
https://github.com/square/workflow/actions/runs/8885992870

**Comment by rjrjr** [comment]
This is working. I'm going to go ahead and merge, TBR @mjohnson12

**Comment by mjohnson12** [comment]
Looks good.

**Pull request merged**
