### PR TITLE
Fix emulators

### LINKED ISSUE #759: Android CI is broken
The android shard for PRs over the last couple days have all been erroring out.

For now, **if you're merging a non-Kotlin/Android PR**, you should go ahead and merge if only the Android shard fails.

### PR DESCRIPTION
**Pull request by jrodbx**
A recent emulator update breaks a few CI projects. This PR applies a fix suggested by Google: https://issuetracker.google.com/issues/145622251#comment33

Fixes #759.

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
Thanks @jrodbx! Can you uncomment the disabled shard in a separate commit so we can actually see what the change is? Or I can take over and do it.

**Comment by jrodbx** [comment]
On it.

**Comment by jrodbx** [comment]
Updated

**Comment by zach-klippenstein** [comment]
Thanks @jrodbx!!

**Pull request merged**
