### PR TITLE
Common sample app gradle config

### PR DESCRIPTION
**Pull request by wugeorgeq**
Taking a stab at [#971 ](https://github.com/square/workflow/issues/971)

### CODE REVIEW

**Comment by wugeorgeq** [comment]
Good call, will do

**Comment by wugeorgeq** [comment]
It looks like we need to write an implementation of `Plugin` to achieve the same goal in kotlin dsl. Going from groovy -> kotlin means going from a dynamic resolution of the scripts to kotlin's static accessor definitions `android{}`, `implementation()` etc. TLDR it's not as simple as converting the common gradle files to `gradle.kts`. @zach-klippenstein, this seems like a good change to do, just wanted to check in to see if this is what we want https://proandroiddev.com/sharing-build-logic-with-kotlin-dsl-203274f73013

**Comment by wugeorgeq** [comment]
Spike here: https://github.com/square/workflow/pull/1086

**Comment by zach-klippenstein** [comment]
Just noticed this is two commits: each commit should be a complete change, so if the first one just adds a file without using it anywhere it looks like dead code. Please squash them, and then we can merge this!

**Pull request merged**
