### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by charbgr**
Per title.

It also opens the way for: https://github.com/square/workflow/issues/51

Closes issue: https://github.com/square/workflow/issues/50, https://github.com/square/workflow/issues/66

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
Thanks! Unfortunately we can't merge this yet because we aren't using AndroidX internally yet, and we need to make sure this doesn't prevent us from consuming the library internally first.

**Comment by charbgr** [comment]
No problem! Ping me to rebase when you are ready!

**Comment by zach-klippenstein** [comment]
We've unblocked ourselves internally, so we can finally do this!

**Comment by charbgr** [comment]
Oh nice! I will try to rebase and continue the implementation asap!

**Comment by charbgr** [comment]
I pushed the latest changes. Let me know what you think!

**Comment by zach-klippenstein** [comment]
This looks good, just going to manually run the sample apps to verify.

**Comment by zach-klippenstein** [comment]
Everything looks good. Thanks again for doing this!

**Pull request merged**
