### PR TITLE
Add link to Kotlin samples

### PR DESCRIPTION
**Pull request by vgonda**
While this section is under construction and does not include Kotlin, point the reader to where they can learn more on their own.

### CODE REVIEW

**Review by dhavalshreyas — APPROVED** [review]
Thank you!

**Comment by vgonda** [comment]
No problem!

@dhavalshreyas The linter is tripping up in files I didn't change. Do I need to update these other files before merging?

**Comment by dhavalshreyas** [comment]
@vgonda would you mind rebasing on latest main?

**Comment by vgonda** [comment]
@dhavalshreyas Rebased!

**Pull request merged**
