### PR TITLE
Rename Kotlin's ViewBinding to ViewFactory.

### LINKED ISSUE #988: Rename ViewBinding to RenderBinding
Android just took over the ViewBinding name, making our use of it super confusing.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
Closes #988.

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
Only failed shard is an unrelated iOS one, this is ready to merge.

**Comment by zach-klippenstein** [comment]
As per [this Slack discussion](https://workflow-community.slack.com/archives/CHTFPR277/p1583514298043300) with @rjrjr and @steveinflow, we've decided to rename `RenderBinding` to `ViewFactory`.

**Comment by rjrjr** [comment]
Offline bike-shed leave me thinking that `ViewFactory` would be a better name. Unclear that anyone else cares. :)

https://workflow-community.slack.com/archives/CHTFPR277/p1583514298043300

**Comment by zach-klippenstein** [comment]
@rjrjr rename is done, ready for another review.

**Comment by zach-klippenstein** [comment]
Yea I'm happy with it too.

**Pull request merged**
