### PR TITLE
Bump gradle to latest version.

### PR DESCRIPTION
**Pull request by zach-klippenstein**

### CODE REVIEW

**Comment by rjrjr** [comment]
Did you actually run the command `./gradlew wrapper --gradle-version 5.4.1`? I expected a bigger diff.

**Comment by rjrjr** [comment]
Could you target the 0.16 branch with this?

**Comment by zach-klippenstein** [comment]
> Did you actually run the command

I did now.

> Could you target the 0.16 branch with this?

Done.

**Comment by rjrjr** [comment]
Yeah, this looks wrong. When I run `./gradlew wrapper --gradle-version 5.4.1` the diff is huge.

**Pull request merged**
